[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = ["./**/*"]

[deploy]
numReplicas = 1
startCommand = ""
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 100
region = "singapore-1"

[deploy.envs]
NODE_ENV = "development"
PORT = "3000"
HOSTNAME = "0.0.0.0"

[[deploy.volumes]]
name = "pages"
path = "/app/app"
mode = "rw"
